[build]
  publish = "."     # или укажи другую папку, если Publish directory у тебя не корень
#eee
[[redirects]]
  from = "/"
  to = "/pages/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/:page"
  to = "/pages/:page.html"
  status = 200
  force = true

[[redirects]]
  from = "/:page/"
  to = "/pages/:page/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/pages/:splat"
  status = 200
  force = true
